import Image from 'next/image'
import styles from './page.module.css'

export const metadata = {
  title: 'John Doe',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className={styles.main}>
    </main>
  )
}
